# Spring Boot
spring.application.name=scraper

# CurroImporter Job properties
curro-importer.data-folder=data/curro-importer
# Input
curro-importer.input.curros-file=${curro-importer.data-folder}/input/curros.csv
# Output
curro-importer.output.curro-info-file=${curro-importer.data-folder}/generated/curro-info.csv
curro-importer.output.company-names-file=${curro-importer.data-folder}/generated/company-names.csv
curro-importer.output.company-info-file=${curro-importer.data-folder}/generated/company-info.csv

# CompanyImporter Job properties
company-importer.data-folder=data/company-importer
# Input
company-importer.input.companies-file=${company-importer.data-folder}/input/company-names.csv
# Output
company-importer.output.company-info-file=${company-importer.data-folder}/generated/company-info.csv
